query($getPostId: ID!) {
  getAllPosts {
    id
    title
    body
    createdAt
  }
  getPost(id: $getPostId) {
    title
    body
  }

  info

  getPostsByLimit{
    paginator {
      currentPage
      postCount
      slNo
      pageCount
      perPage
    }
    posts {
      id
      title
      body
      author {
        id
        first_Name
        avatarImage
      }
    }
  }
}

mutation($getPostId: ID!, $file: FileUpload!) {
  createNewPost (inputPost:{
    title:"wrong Post by anshu"
    body: " lets joy out as it is our third (anshu)post out in yellow"
  }){
    id
    title
    body
    author {
      avatarImage
      username
      first_Name
    }
  }

  deletePost(id: $getPostId) {
    title
    body
    author {
      avatarImage
      username
      first_Name
    }
  }

  updatePost(
    id: $getPostId
    inputPost: { title: "second post updated with new", body: "lets enjoy the day" }
  ) {
    title
    body
  }

  imageUploader(file: $file)
}

query ($getUserId: ID!) {
  helloUser

  getAllUsers {
    id
    first_Name
    last_Name
  }
  getUser(id: $getUserId) {
    first_Name
  }
}

query ($username: String!, $password: String!) {
  loginUser(username: $username, password: $password) {
    token
    user {
      first_Name
      last_Name
    }
  }
  authenticatedUser{
    first_Name
    username
    id
  }
}
mutation{

  registerNewUser(user: {
    username:"anstar"
    email:"anhsumanswain@gmail.com"
    first_Name:"Anshu"
    password:"asdfghjk"
  }) {
    token
    user {
      username
      first_Name
      email
    }
  }

}

#variables
{
  "username": "anshu",
  "password": "asdfghjk",
  "getUserId": "630f0dd98ae55a919b977b09",
  "getPostId": "6314bf294cb233747342409a"
  
}

#Header

# authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMGYwZGQ5OGFlNTVhOTE5Yjk3N2IwOSIsInVzZXJuYW1lIjoiYW5zaHUiLCJlbWFpbCI6ImFuaHN1bWFuc3dhaW5AZ21haWwuY29tIiwiZmlyc3RfTmFtZSI6IkFuc2h1IiwiYXZhdGFySW1hZ2UiOiJodHRwczovL2Nkbi1pY29ucy1wbmcuZmxhdGljb24uY29tLzUxMi8xMDUzLzEwNTMyNDQucG5nP3c9MzYwIiwiaWF0IjoxNjYyMjY5OTQyLCJleHAiOjE2NjI4NzQ3NDJ9.qRCIyxNincvG76_08ueUW_Vgd_M5PmjeBdnruKJLw0Y

# directives----------------------------------------------/ Examples

query ($isAuthenticated: Boolean! = false) { # false is default value
  getAllPosts {
    id @skip(if: $isAuthenticated)
    ... on Post @include(if:$isAuthenticated) { #this is together with the include directive
      body
      imageLink
      createdAt
    }
    user @include(if:$isAuthenticated)
  }
}
