query($getPostId: ID!) {
  getAllPosts {
    id
    title
    body
    createdAt
  }
  getPost(id: $getPostId) {
    title
    body
  }
}

mutation($getPostId: ID!) {
  createNewPost (inputPost:{
    title:"fourth Post"
    body: " lets joy out as it is our fourth post out in yellow"
  }){
    title
    body
  }

  deletePost(id: $getPostId) {
    title
    body
  }

  updatePost(
    id: $getPostId
    inputPost: { title: "second post updated with new", body: "lets enjoy the day" }
  ) {
    title
    body
  }
}

#variables
{
  "getPostId": "630d9dcedd382e2b8a95e674",
}

# directives----------------------------------------------/ Examples

query ($isAuthenticated: Boolean! = false) { # false is default value
  getAllPosts {
    id @skip(if: $isAuthenticated)
    ... on Post @include(if:$isAuthenticated) { #this is together with the include directive
      body
      imageLink
      createdAt
    }
    user @include(if:$isAuthenticated)
  }
}
